Repository andela/zinnia-ah-frontend, pull requests merged in 2019-05, with the labels that each got.

#7 #165798066 ch setup heroku deployment
  .gitignore
  package-lock.json
  package.json
  server.js
Labels: ready for review

#8 164797109 user can login
  .babelrc
  .eslintignore
  .prettierignore
  package-lock.json
  package.json
  src/Index.jsx
  src/Routes.jsx
  src/api/auth.js
  src/api/client.js
  src/api/helpers.js
  src/api/helpers.test.js
  src/assets/_variables.scss
  src/assets/images/facebook-icon.svg
  src/assets/images/google-icon.svg
  src/assets/images/reading-lady.svg
  src/assets/images/twitter-icon.svg
  src/components/App.jsx
  src/components/App.scss
  src/components/App.test.jsx
  src/components/Register/Register.jsx
  src/components/__snapshots__/App.test.jsx.snap
  src/components/container/Register/Register.jsx
  src/components/container/Register/Register.test.jsx
  src/components/container/Register/__snapshots__/Register.test.jsx.snap
  src/components/container/login/__snapshots__/loginComponent.test.jsx.snap
  src/components/container/login/loginComponent.jsx
  src/components/container/login/loginComponent.test.jsx
  src/components/presentationals/AuthenticationCard.jsx
  src/components/presentationals/AuthenticationCard/AuthenticationCard.jsx
  src/components/presentationals/AuthenticationCard/AuthenticationCard.scss
  src/components/presentationals/AuthenticationIllustration/AuthenticationIllustration.jsx
  src/components/presentationals/AuthenticationIllustration/AuthenticationIllustration.scss
  src/components/presentationals/Avatar/Avatar.jsx
  src/components/presentationals/Avatar/Avatar.scss
  src/components/presentationals/Button/Button.jsx
  src/components/presentationals/Button/Button.scss
  src/components/presentationals/ForgotPassword/ForgotPassword.jsx
  src/components/presentationals/Form.scss
  src/components/presentationals/Input/Input.jsx
  src/components/presentationals/Navbar/Navbar.jsx
  src/components/presentationals/Navbar/Navbar.scss
  src/components/presentationals/ResetPassword/ResetPassword.jsx
  src/components/presentationals/Title/Title.jsx
  src/pages/Authentication.jsx
  src/pages/Authentication.scss
  src/pages/ForgotPassword.jsx
  src/pages/ResetPassword.jsx
  src/setupTests.js
  src/store/modules/auth.js
  src/store/modules/auth.test.js
  src/store/rootReducer.js
  src/store/store.js
  src/utils/formValidator.js
  src/utils/formValidator.test.js
  webpack.config.js
Labels: approval needed, feedback implemented, ready for review

#12 #164797111 User should be able to see their profile
  package-lock.json
  package.json
  src/Routes.jsx
  src/assets/_variables.scss
  src/components/presentationals/ArticleLists/ArticleLists.jsx
  src/components/presentationals/ArticleLists/ArticleLists.test.jsx
  src/components/presentationals/ArticleLists/__snapshots__/ArticleLists.test.jsx.snap
  src/components/presentationals/AuthenticationIllustration/AuthenticationIllustration.test.jsx
  src/components/presentationals/AuthenticationIllustration/__snapshots__/AuthenticationIllustration.test.jsx.snap
  src/components/presentationals/Avatar/Avatar.jsx
  src/components/presentationals/Avatar/Avatar.scss
  src/components/presentationals/Avatar/Avatar.test.jsx
  src/components/presentationals/Avatar/__snapshots__/Avatar.test.jsx.snap
  src/components/presentationals/Button/Button.test.jsx
  src/components/presentationals/Button/__snapshots__/Button.test.jsx.snap
  src/components/presentationals/ForgotPassword/ForgotPasswordCard.jsx
  src/components/presentationals/ForgotPassword/ForgotPasswordCard.test.jsx
  src/components/presentationals/ForgotPassword/__snapshots__/ForgotPasswordCard.test.jsx.snap
  src/components/presentationals/Navbar/Navbar.jsx
  src/components/presentationals/Navbar/Navbar.test.jsx
  src/components/presentationals/Navbar/__snapshots__/Navbar.test.jsx.snap
  src/components/presentationals/ProfileMain/ProfileMain.jsx
  src/components/presentationals/ProfileMain/ProfileMain.scss
  src/components/presentationals/ProfileMain/ProfileMain.test.jsx
  src/components/presentationals/ProfileMain/__snapshots__/ProfileMain.test.jsx.snap
  src/components/presentationals/ProfileSidebar/ProfileSidebar.jsx
  src/components/presentationals/ProfileSidebar/ProfileSidebar.scss
  src/components/presentationals/ProfileSidebar/ProfileSidebar.test.jsx
  src/components/presentationals/ProfileSidebar/__snapshots__/ProfileSidebar.test.jsx.snap
  src/components/presentationals/Title/Title.test.jsx
  src/components/presentationals/Title/__snapshots__/Title.test.jsx.snap
  src/pages/ForgotPassword.jsx
  src/pages/Profile.jsx
  src/pages/Profile.scss
  src/pages/Profile.test.js
  src/pages/__snapshots__/Profile.test.js.snap
  src/store/modules/profile.js
  src/store/modules/profile.test.js
  src/store/rootReducer.js
  src/utils/config.js
  webpack.config.js
Labels: approval needed, feedback implemented, ready for review

#16 #164797112 Implement delete article
  src/Routes.jsx
  src/api/client.js
  src/api/profile.js
  src/components/presentationals/ArticleLists/ArticleLists.jsx
  src/components/presentationals/ArticleLists/ArticleLists.test.jsx
  src/components/presentationals/ArticleLists/__snapshots__/ArticleLists.test.jsx.snap
  src/components/presentationals/Button/Button.scss
  src/components/presentationals/ProfileMain/ProfileMain.jsx
  src/components/presentationals/ProfileMain/ProfileMain.test.jsx
  src/components/presentationals/ProfileMain/__snapshots__/ProfileMain.test.jsx.snap
  src/pages/Profile.jsx
  src/pages/Profile.scss
  src/pages/Profile.test.js
  src/pages/__snapshots__/Profile.test.js.snap
  src/store/modules/profile.js
  src/store/modules/profile.test.js
Labels: approval needed, ready for review

#10 #164797111 ft edit user profile
  .env.example
  package-lock.json
  package.json
  src/Index.jsx
  src/Routes.jsx
  src/api/client.js
  src/api/helpers.test.js
  src/assets/_variables.scss
  src/components/presentationals/Avatar/Avatar.scss
  src/components/presentationals/Form.scss
  src/components/presentationals/ProfileMain/ProfileMain.jsx
  src/components/presentationals/ProfileMain/ProfileMain.test.jsx
  src/components/presentationals/ProfileMain/__snapshots__/ProfileMain.test.jsx.snap
  src/components/presentationals/ProfileSettings/ProfileSettings.jsx
  src/components/presentationals/ProfileSettings/ProfileSettings.test.jsx
  src/components/presentationals/ProfileSettings/__snapshots__/ProfileSettings.test.jsx.snap
  src/components/presentationals/ProfileSidebar/ProfileSidebar.jsx
  src/config/config.js
  src/pages/ForgotPassword.jsx
  src/pages/Profile.jsx
  src/pages/__snapshots__/Profile.test.js.snap
  src/store/actions/updateProfileActions.js
  src/store/modules/profile.js
  src/store/reducer.js
  src/utils/helpers.js
  src/utils/helpers.test.js
  webpack.config.js
Labels: approval needed, ready for review

#15 #164797110 setup social login with google, facebook and twitter
  package-lock.json
  package.json
  src/Routes.jsx
  src/api/helpers.js
  src/components/App.jsx
  src/components/__snapshots__/App.test.jsx.snap
  src/components/presentationals/ArticleLists/ArticleLists.jsx
  src/components/presentationals/ArticleLists/__snapshots__/ArticleLists.test.jsx.snap
  src/components/presentationals/AuthenticationCard/AuthenticationCard.jsx
  src/components/presentationals/AuthenticationCard/AuthenticationCard.test.jsx
  src/components/presentationals/AuthenticationCard/__snapshots__/AuthenticationCard.test.jsx.snap
  src/components/presentationals/Button/Button.jsx
  src/components/presentationals/SocialAuth/SocialAuth.jsx
  src/components/presentationals/SocialAuth/SocialAuth.test.jsx
  src/config/config.js
  src/pages/Authentication.jsx
  src/pages/ForgotPassword.jsx
  src/pages/ResetPassword.jsx
  src/store/modules/auth.js
  src/store/modules/auth.test.js
  src/utils/testHelpers.js
Labels: approval needed, ready for review

#18 #164797125 User should be able to see list of their bookmarked articles
  package-lock.json
  package.json
  src/api/profile.js
  src/components/container/BookmarkLists/BookmarkLists.jsx
  src/components/container/BookmarkLists/BookmarkLists.test.jsx
  src/components/container/BookmarkLists/__snapshots__/BookmarkLists.test.jsx.snap
  src/components/presentationals/ArticleLists/ArticleLists.jsx
  src/components/presentationals/ArticleLists/ArticleLists.test.jsx
  src/components/presentationals/ArticleLists/__snapshots__/ArticleLists.test.jsx.snap
  src/components/presentationals/ProfileMain/ProfileMain.jsx
  src/components/presentationals/ProfileMain/ProfileMain.test.jsx
  src/components/presentationals/ProfileMain/__snapshots__/ProfileMain.test.jsx.snap
  src/components/presentationals/ProfileSettings/ProfileSettings.test.jsx
  src/pages/Profile.test.js
  src/pages/__snapshots__/Profile.test.js.snap
  src/store/modules/profile.js
  src/store/modules/profile.test.js
Labels: approval needed, ready for review

#24 #166095506 fixed heroku environemtal load
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/api/client.js
  src/components/container/BookmarkLists/__snapshots__/BookmarkLists.test.jsx.snap
  src/config/config.js
  src/utils/helpers.js
  webpack.config.js
Labels: feedback implemented, ready for review

#20 164797112 Users can read articles
  src/Routes.jsx
  src/api/article.js
  src/api/client.js
  src/components/container/BookmarkLists/BookmarkLists.jsx
  src/components/container/BookmarkLists/BookmarkLists.test.jsx
  src/components/container/BookmarkLists/__snapshots__/BookmarkLists.test.jsx.snap
  src/components/presentationals/ArticleLists/ArticleLists.jsx
  src/components/presentationals/ArticleLists/ArticleLists.test.jsx
  src/components/presentationals/ArticleLists/__snapshots__/ArticleLists.test.jsx.snap
  src/components/presentationals/Author/Author.jsx
  src/components/presentationals/Author/Author.test.jsx
  src/components/presentationals/Author/__snapshots__/Author.test.jsx.snap
  src/config/config.js
  src/pages/Article.jsx
  src/pages/Article.scss
  src/pages/Article.test.jsx
  src/pages/__snapshots__/Article.test.jsx.snap
  src/store/modules/article.js
  src/store/modules/article.test.js
  src/store/rootReducer.js
  src/utils/helpers.js
Labels: approval needed, ready for review
